### PR TITLE
Added some enhancements for ESP8266 version

### PR DESCRIPTION
**Pull request by jofland**
Added:
- ESP8266 version
- retry timeout for dht sensor
- mqtt data transmission
- PCB layout for Wemos D1 Mini
- config files for telgraf and grafana

### CODE REVIEW

**Comment by werner-rh** [comment]
I've created a new branch ESP8266-grafana, because this changes are very special. Especially the grafana stuf is far above an average Arduini newbie. Please add your changes to branch mentioned above.

I don't know about your knowledge working with github or any code repositries in professional environment.
By working in teams, following steps are mandatory:

1. never, never, never work directly on the main branch!
2. create a new branch (if you are not able to, maybe it's not granted, ask for)
3. work on the new branch and add your changes there.
4. Don't forget versioning, changelog.md and readme.md ( i saw it)

This PR will be refected because of reasons above.

**Comment by werner-rh** [comment]
This PR can't be merged into the main branch.

**Comment by jofland** [comment]
Thank you for your message an your help.

Actually this is my first time to contribute some code to another repository an my first time using github for code management.

I will try to check out your new branch, put my fork into it, complement the changelog and initiate a new PR. Right?

**Comment by werner-rh** [comment]
Yes. But you should be able to handle it your self. Normal process: create a new branch. This should be created in your case from the ESP32 branch. You can name the brunch as you like. The name should be a little bit self speaking like "ESP32-feature-XY". Then push your changes into the new branch, create a PR, review and aprove and finaly merge it into the destionation branch. In this case it should be the ESP32 branch.

**Pull request closed without merging**
