### PR TITLE
Esp8266 grafana jofland

### PR DESCRIPTION
**Pull request by jofland**
Hi Werner,

I hope I did it right this time:

- checked out your branch ESP8266-grafana as local branch in my repository
- merged my fork into the local branch
- changed version to 0.50 in README.md and DryBoxControl.h
- edited CHANGELOG.md
- pushed my local branch to my forked repository
- PR against your branch ESP8266-grafana

Should I do the versioning any different than in README.md and DryBoxControl.h?

Regarding the diff view in github´s PR, as I see it below this message box: github shows 100% differences of changed files even if I only changed one line (e.g. DryBoxControl.h). For other files (e.g. CHANGELOG.md) it shows only the changed lines. Any ideas why? For both of us it would have been more convenient to see only the differing lines. 

When should I merge my branch into the main branch of my forked repository? I suspect this should be obsolete when you accepted my PR  and merged it into your main branch, right?

Please let me know if I should do something different. I hope the project will develop and help other users.

Kind regards, Jens

### CODE REVIEW

**Comment by werner-rh** [comment]
Hi Jens,
the 100% might due to the new branch. But i am not 100% shure. I will merge your changes into the new branch. After this should be the same as your fork. Please be so kind and cross check if everything works fine after merging. Nothing is more frustrating for beginners, when they are not able to compile the code because some files are forgotten or similar stuf.

I think the versioning is fine in this way. I will investigate, if it is possible and how i can grant you more permissions to this branch. So you should be able to create new branches from the ESP32-Grafana fork in this repository. In our company we work with bitbucket, so i have to take a look, how it works in github.

Best regards, Werner

**Comment by jofland** [comment]
Hi Werner,

I did some QS checks.

First: Branch werner-rh:ESP8266-grafana in your repository matches my fork. PR was successful. So my fork in my repository is obsolete.

Diff with KDiff3 between branch ESP8266-grafana and the main branch displayed only the expected differences (in opposite to the 100% diff with git´s build in diff too). So (nearly) everything seems to be OK. I found one real issue in my code that i will fix in branch ESP8266-grafana and some cosmetic differences which don´t matter for function:
- different block comment style: branch has no asterisk leading commented lines while main branch has (maybe someone between version 0.48 and 0.49.1 used a different editor
- same for number of leading spaces in some indented function blocks
- some files have different line endings (dos/unix)

I hope we can go to main branch after my fix (hope your invitation works) and after merging changes from 0.49 and 0.49.1 into branch ESP8266-grafana. I will let you know when I am done.

I did not run the branch on arduino hardware to test functionality because I don´t have a separate display.

Regards, Jens

**Comment by jofland** [comment]
Hi Werner,

I am finish:
- merged changes from 0.49 and 0.49.1 into branch ESP8266-grafana
- fix bug in my forked code
- added robustness so that ESP8266 version runs even without configured wifi or mqtt broker
- tested on ESP8266 hardware
- did a compile test for arduino

I left the version at 0.50 as the branch is the highest version at the moment.

Feel free to check an merge to main branch. After this I would like to link my printables remix description to your git repository main branch.

Regards, Jens

**Comment by werner-rh** [comment]
Hi, currently i have no ESP32. So i can't verify this. I would suggest to keep the ESP stuff in the ESP8266-grafana branch as an own version. You can also link directly to this branch.

Best regards, Werner

**Comment by jofland** [comment]
Hi Werner,

I have some changes in the ESP8266 branch. Mainly in the Readme file for troubleshooting. How should we version ESP branch? At the moment it´s Version 50 based on the main version 49. You have committed a V 49.1 already in main branch.

I would suggest the following options:

1. Stay on V 50 and add a subversion for the esp branch´s changes. E.g. V 50 ESP 01; V50 ESP 02 and so on.
2. Independent version count in main branch and esp branch. ESP´s next version would be V 51. Main branch could have independent V50 and V51.

What do you think? My favorite ist option 1.

Regards, Jens

**Comment by werner-rh** [comment]
Hi Jens,
i think option 1 is a good choice. In near future i will set the version also to V50 to indicate that is the same base. So we have an equal version number and extra counting for ESP.

Best regards, Werner

**Pull request merged**
